// This file is generated by Firebase Extensions.
'use server';
/**
 * @fileOverview AI agent that recommends songs based on listening habits.
 *
 * - recommendSongs - A function that handles the song recommendation process.
 * - RecommendSongsInput - The input type for the recommendSongs function.
 * - RecommendSongsOutput - The return type for the recommendSongs function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RecommendSongsInputSchema = z.object({
  listeningHistory: z
    .string()
    .describe(
      'A detailed history of the user listening habits, including songs, artists, genres, and listening frequency.'
    ),
});
export type RecommendSongsInput = z.infer<typeof RecommendSongsInputSchema>;

const RecommendSongsOutputSchema = z.object({
  recommendations: z
    .array(z.string())
    .describe('A list of song recommendations based on the listening history.'),
  reasoning: z
    .string()
    .describe('Explanation of why these songs were recommended.'),
});
export type RecommendSongsOutput = z.infer<typeof RecommendSongsOutputSchema>;

export async function recommendSongs(input: RecommendSongsInput): Promise<RecommendSongsOutput> {
  return recommendSongsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'recommendSongsPrompt',
  input: {schema: RecommendSongsInputSchema},
  output: {schema: RecommendSongsOutputSchema},
  prompt: `You are a music recommendation expert. Analyze the user's listening history and provide song recommendations.

Listening History: {{{listeningHistory}}}

Based on this listening history, recommend songs that the user might like. Explain your reasoning for each recommendation.

Format your response as follows:

Recommendations:
- Song 1 - Reasoning
- Song 2 - Reasoning
...

Reasoning: Provide a summary of why these songs were selected based on the listening history.

Here are the recommendation steps:
1. Extract the artist, songs and music genre the user listen to
2. Check on new released songs or the song that the user doesn't listen to before
3. Pick the most similar genre songs to recommend to the user
4. Reasoning the recommendation
`,
});

const recommendSongsFlow = ai.defineFlow(
  {
    name: 'recommendSongsFlow',
    inputSchema: RecommendSongsInputSchema,
    outputSchema: RecommendSongsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
